project_id = "kdmruvwgxepwiwppuzlj"
[functions.github-actions]
verify_jwt = false

[functions.github-actions-webhook]
verify_jwt = false

[functions.test-run-webhook]
verify_jwt = false

[functions.cypress-events]
verify_jwt = false
